apiVersion: v1
kind: Service
metadata:
  name: gcp-cicd
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "gcp-cicd-backendconfig"}'
spec:
  selector:
    app: gcp-cicd
  ports:
    - port: 80
      targetPort: 80
