name: Release and Deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: graphic-matrix-481507-u5 # ðŸ”´ Ensure this matches your GCP project
  REGION: us-east1 # ðŸ”´ Ensure this matches your GKE cluster region
  REPOSITORY: gcp-cicd
  IMAGE_NAME: gcp-cicd
  GKE_CLUSTER_NAME: gcpcicd # ðŸ”´ Ensure this matches your GKE cluster name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $REGION --project $PROJECT_ID

      - name: Set up Kustomize
        run: |
          rm -rf kustomize
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Deploy with Kustomize
        run: |
          kustomize build kustomize/overlays/production | kubectl apply -f -
