name: Release and Deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: graphic-matrix-481507-u5 # ðŸ”´ CHANGE THIS
  REGION: us-east1 # ðŸ”´ CHANGE IF NEEDED
  REPOSITORY: gcp-cicd # ðŸ”´ CHANGE IF NEEDED
  IMAGE_NAME: gcp-cicd # ðŸ”´ CHANGE IF YOU WANT

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region $REGION --project $PROJECT_ID

      - name: Set up Kustomize
        run: |
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/latest/download/kustomize_$(uname -s)_$(uname -m)
          chmod u+x ./kustomize
          sudo mv ./kustomize /usr/local/bin/

      - name: Deploy with Kustomize
        run: |
          kustomize build kustomize/overlays/production | kubectl apply -f -
