apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gcpcicd-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: gcpcicd-ssl
spec:
  defaultBackend:
    service:
      name: gcp-cicd
      port:
        number: 80
  rules:
    - host: gcpcicd.anand.theraut.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gcp-cicd
                port:
                  number: 80
