apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gcp-cicd-ingress
  annotations:
    networking.gke.io/managed-certificates: my-ssl-cert
spec:
  rules:
    - host: gcpcicd.anand.theraut.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gcp-cicd
                port:
                  number: 80
