apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - deployment.yaml
  - managed-cert.yaml
  - ingress.yaml
  - backend-config.yaml

namespace: production

images:
  - name: us-east1-docker.pkg.dev/graphic-matrix-481507-u5/gcp-cicd/gcp-cicd
    newTag: #{IMAGE_TAG}#
