apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

bases:
  - ../base

resources:
  - deployment.yaml
  - managed-cert.yaml
  - ingress.yaml
  - backend-config.yaml
